# Generated by Django 5.0.6 on 2024-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr2', '0003_cargo_alter_trabajador_edad_alter_trabajador_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
