# Generated by Django 5.0.6 on 2024-06-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr2', '0005_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
