# Generated by Django 5.0.6 on 2024-06-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr2', '0008_rename_password_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
